# Generated by Django 4.0.5 on 2022-07-26 19:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0001_initial'),
        ('livros_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='data_devolucao',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='data_emprestimo',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='nome_emprestado',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='tempo_duracao',
        ),
        migrations.AddField(
            model_name='categoria',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios_app.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='capa_livro'),
        ),
        migrations.AddField(
            model_name='livros',
            name='usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios_app.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livros',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livros_app.categoria'),
        ),
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_emprestado_anonimo', models.CharField(blank=True, max_length=30, null=True)),
                ('data_emprestimo', models.DateTimeField(default=datetime.datetime(2022, 7, 26, 16, 58, 47, 447903))),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('avaliacao', models.CharField(blank=True, choices=[('P', 'Péssimo'), ('R', 'Ruim'), ('B', 'Bom'), ('O', 'Ótimo')], max_length=1, null=True)),
                ('livro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livros_app.livros')),
                ('nome_emprestado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios_app.usuario')),
            ],
        ),
    ]
