# Generated by Django 4.0.5 on 2022-07-26 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros_app', '0002_remove_livros_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 17, 11, 36, 801667)),
        ),
        migrations.AlterField(
            model_name='livros',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='capa_livro'),
        ),
    ]
