# Generated by Django 4.0.5 on 2022-06-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros_app', '0002_alter_livros_options_alter_livros_co_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(auto_now=True),
        ),
    ]
