# Generated by Django 4.0.5 on 2022-07-26 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros_app', '0003_alter_emprestimos_data_emprestimo_alter_livros_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 17, 18, 55, 660907)),
        ),
        migrations.AlterField(
            model_name='livros',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='capa_livro/'),
        ),
    ]
