# Generated by Django 4.0.5 on 2022-07-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros_app', '0005_emprestimos_nome_emprestado_anonimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
