# Generated by Django 4.0.5 on 2022-07-22 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros_app', '0006_alter_emprestimos_data_devolucao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='tempo_duracao',
        ),
    ]
