# Generated by Django 4.0.5 on 2022-07-24 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros_app', '0010_alter_emprestimos_data_emprestimo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='avaliacao',
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 9, 45, 27, 813792)),
        ),
    ]
