# Generated by Django 4.0.5 on 2022-07-26 13:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livros_app', '0013_alter_emprestimos_data_emprestimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 10, 15, 0, 1107)),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livros_app.livros'),
        ),
    ]
