# Generated by Django 4.0.5 on 2022-07-26 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros_app', '0014_alter_emprestimos_data_emprestimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 10, 28, 59, 246913)),
        ),
    ]
